# Generated by Django 4.1.4 on 2022-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=1000000),
        ),
    ]
