# Generated by Django 4.1.4 on 2022-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
